### PR TITLE
Make tasks cancellable

### PR DESCRIPTION
**Pull request by aosagie**
First of all, thanks for this useful library. I've used it on multiple projects, but I've repeatedly been unable to test business logic that utilized cancellations. I know you're trying to avoid complexity, but I think this implementation is simple enough.

### CODE REVIEW

**Comment by miguno** [comment]
Thanks, @aosagie.  I'll take a look!

**Comment by miguno** [comment]
I refactored your changes a bit -- feel free to take a look at the branch [`aosagie-feature/cancellable-tasks`](https://github.com/miguno/akka-mock-scheduler/tree/aosagie-feature/cancellable-tasks) and let me know if this code would work for you.

Edit: For reference here is a direct link to [comments/feedback for this branch](https://github.com/miguno/akka-mock-scheduler/commit/3f39f6230e1e2fc895aabaca668532d34f7294ca).

**Comment by jozic** [comment]
would be nice to have a fresh release with it as soon as it's in

**Comment by dobrek** [comment]
@miguno Is there any chance to merge this PR soon? It will be really nice to have such a feature :)

**Comment by pmiddend** [comment]
I would also like to have this feature.

**Comment by miguno** [comment]
I haven't forgotten about this PR but haven't found the time yet to follow up.  It's on my todo list though, and my plan is to have an update sometime next week.

**Comment by aosagie** [comment]
Hey @miguno, is it possible this PR can get merged since it's rather small, and the relatively larger refactor you planned for it can be saved for later? I know a lot of people personally who'd like to use this feature.

**Comment by mmacfadden** [comment]
I would also vote for this.  I would be happy to help if need be.

**Comment by miguno** [comment]
Fixed in release `0.4.0` (currently being synced via Sonatype to Maven Central, might take a few hours).  Thanks for your patience, everyone!  This took much longer than I wanted, really.

**Pull request closed without merging**
