### PR TITLE
Compile and test with 2.13.0-M5

### PR DESCRIPTION
**Pull request by 2m**
Towards fixing #13

### CODE REVIEW

**Comment by miguno** [comment]
Thanks for this PR, @2m! Much appreciated. :-)

I have to admit that I didn't spot https://github.com/miguno/akka-mock-scheduler/issues/13, which you raised earlier. Sorry!

**Comment by miguno** [comment]
In general I'm +1 on the PR, but one question: why should it use 2.13 M5 instead of RC1 (which was released early April)?

**Comment by 2m** [comment]
That would require upgrading scalatest to `3.0.8-RC2` as that seems to be the only version that is cross published for 2.11.x 2.12.x and 2.13.0-RC1 https://mvnrepository.com/artifact/org.scalatest/scalatest

Would that be fine?

**Comment by miguno** [comment]
Ah, I see. Then let's keep M5 for now. I'll merge your PR.

**Comment by miguno** [comment]
I will publish a 2.13 artifact once 2.13 is officially available.

**Comment by 2m** [comment]
Great, thanks.

**Pull request merged**
