### PR TITLE
Bump dependency versions, scala 2.12

### PR DESCRIPTION
**Pull request by koshelev**
- Update Akka 2.4.14, which leads to dropping support of scala 2.10.x.
- scala 2.11.8 default scala version
- support scala 2.12.0

### CODE REVIEW

**Comment by miguno** [comment]
Thanks, @koshelev!

I made a couple of further commits to update all the various dependencies, and also bumped the version to `0.5.0-SNAPSHOT`.  I also published the latest snapshot (for Scala 2.11/2.12 and Java 8+) to Sonatype.

**Comment by koshelev** [comment]
Any plans to release 0.5.0?

**Comment by miguno** [comment]
It's already available in the Sonatype repository as `0.5.0-SNAPSHOT`, see the README for details.  The release version may follow a few days later.

**Comment by koshelev** [comment]
I'm using the snapshot version already. Just waiting for a release to get rid of the snapshot in project dependencies, but as it is in test scope, can wait some days more. Thanks!

**Comment by miguno** [comment]
@koshelev: Just pushed the `0.5.0` release to Sonatype, the artifacts should hit Maven Central in the next few hours. Hope that helps!

**Comment by koshelev** [comment]
Thanks a lot!

**Pull request merged**
